name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Grant execute permission to mvnw
      working-directory: ./JWT Authentication System/jwt-auth-backend
      run: chmod +x mvnw
    - name: Build with Maven
      working-directory: ./JWT Authentication System/jwt-auth-backend
      run: ./mvnw clean compile
